 name: Vue CI
 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Use Vue JS ${{ matrix.node-version }}
     - run: |
             npm ci
             npm run build
             npm run test:unit
             npm run lint
